#!/usr/bin/python3

from pathlib import Path

from src.checker import Checker
from src.config import Configuration
from src.salutem import Salutem
from src.printer import Printer


if __name__ == '__main__':

    salutem = Salutem()

    print_with_color = bool(salutem.args.colored)
    stop_on_failure = bool(salutem.args.stop_on_failure)
    only_show_failures = bool(salutem.args.only_show_failures)

    checker = Checker(
        Configuration(
            str(Path.home()) + '/.config/salutem/checks',
            stop_on_failure,
            only_show_failures
        ),
        Printer(print_with_color)
    )

    checker.check()
