#!/usr/bin/python3
from src.checker import Checker
from src.config import Configuration
from src.salutem import Salutem
from src.printer import Printer


if __name__ == '__main__':

    salutem = Salutem()

    print_with_color = True if salutem.args.colored else False
    stop_on_failure = True if salutem.args.stop_on_failure else False
    only_show_failures = True if salutem.args.only_show_failures else False



    checker = Checker(
        Configuration(
            '/home/joe/.config/salutem/checks',
            stop_on_failure,
            only_show_failures
        ),
        Printer(print_with_color)
    )

    checker.check()
